# Project
version=1.2.3
group=com.practicalenchantments
java_version=25
# Common
minecraft_version=26.2
mod_name=Practical Enchantments
mod_author=Huziyang520
mod_id=practical_enchantments
license=MIT
credits=
description=Adds practical custom enchantments to Minecraft 26.2. Issues: https://issue.mengcai.online/
minecraft_version_range=[26.2, 26.3)
# neoForm version used by the common module (official mappings)
neo_form_version=26.2-1
# Fabric
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3
# NeoForge
neoforge_version=26.2.0.86
neoforge_loader_version_range=[4,)
# EnchantLib dependency version
enchantlib_version=1.3.3
# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
